name: Build signed app
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
        
    steps:
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install rename
    
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Build release app
        uses: gradle/gradle-command-action@v2
        with:
          arguments: assembleRelease

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'ThePBone/XTimeMachine'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: test
          name: XTimeMachine test
         # body: "${{ steps.changelog.outputs.changelog }} &#x20; ${{ steps.changelog_post.outputs.contents }}"
          #files: |
          #   app/build/outputs/apk/${{ env.BUILD_TYPE }}/*-signed.apk
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: 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
